(ns org.replikativ.persistent-sorted-set.test.fressian-compat
  "The persisted-Fressian COMPATIBILITY ORACLE.

   Fressian is a shipped, on-disk format. Extracting the node codec into
   `impl.nodes` rewrote every write and read path it uses, and a drift there does
   not fail loudly — it silently misreads stores that already exist on users'
   disks.

   `test.fressian-handlers` cannot catch that. It round-trips the CURRENT writer
   through the CURRENT reader, so it stays green if both ends drift together, in
   the same direction, at the same time — which is exactly what a refactor that
   moves both does.

   So this namespace tests against BYTES, not behaviour, from
   `test-resources/fressian-golden-0.4.137.edn`: blobs generated by the
   PRE-refactor code (0.4.137, the last release before `impl.nodes` existed) and
   committed. Two directions, and both matter:

     READ  — the current reader must decode those bytes to the right elements.
             Catches a reader that stopped understanding old blobs.
     WRITE — re-encoding what we decoded must reproduce the SAME bytes.
             Catches a writer that still reads old data but emits something new,
             which splits a deployment in half the moment one node upgrades.

   Regenerating these fixtures from the current tree would defeat the whole
   purpose — the generator lives at `dev/gen_golden.clj` and must be run against
   the 0.4.137 tag."
  (:require [clojure.test :refer [deftest is testing]]
            [org.replikativ.persistent-sorted-set :as set]
            [org.replikativ.persistent-sorted-set.fressian :as pss-fress]
            [org.replikativ.persistent-sorted-set.boundary :as bnd]
            [clojure.edn :as edn]
            #?(:clj [clojure.java.io :as io])
            #?(:clj [clojure.data.fressian :as fress]))
  #?(:clj (:import [org.replikativ.persistent_sorted_set IStorage PersistentSortedSet]
                   [java.io ByteArrayOutputStream ByteArrayInputStream])))

;; JVM only: the fixtures were produced by data.fressian, and this asserts on ITS bytes.
;; The cljs codec is covered by test.fressian-handlers; what is at stake here is the
;; persisted JVM format that existing stores are written in.
#?(:clj
   (do
     (def golden
       (delay (edn/read-string (slurp (io/resource "fressian-golden-0.4.137.edn")))))

     (defn- unhex ^bytes [s]
       (let [n (quot (count s) 2) a (byte-array n)]
         (dotimes [i n]
           (aset a i (unchecked-byte (Integer/parseInt (subs s (* 2 i) (+ 2 (* 2 i))) 16))))
         a))

     (defn- hex [^bytes bs]
       (apply str (map #(format "%02x" (bit-and % 0xff)) bs)))

     (def ^:private write-lookup
       (-> (merge fress/clojure-write-handlers pss-fress/write-handlers)
           fress/associative-lookup fress/inheritance-lookup))

     (defn- read-lookup [bf]
       (-> (merge fress/clojure-read-handlers
                  (pss-fress/read-handlers {:default-bf bf
                                            :boundary-resolver bnd/boundary-from-descriptor}))
           fress/associative-lookup))

     (defn- ser ^bytes [node lk]
       (let [out (ByteArrayOutputStream.)]
         (.writeObject (fress/create-writer out :handlers lk) node)
         (.toByteArray out)))

     (defn- deser [^bytes bs lk]
       (.readObject (fress/create-reader (ByteArrayInputStream. bs) :handlers lk)))

     ;; Reads the committed fixtures; `store` re-serializes with the CURRENT writer so a
     ;; restore+mutate+store cycle is exercised against old data too.
     (defrecord GoldenStorage [*blobs bf]
       IStorage
       (store    [_ node] (let [a (str (random-uuid))]
                            (swap! *blobs assoc a (hex (ser node write-lookup))) a))
       (accessed [_ _addr] nil)
       (restore  [_ addr] (deser (unhex (get @*blobs addr)) (read-lookup bf)))
       (markFreed [_ _addr] nil) (isFreed [_ _addr] false) (freedInfo [_ _addr] nil))

     (deftest golden-blobs-still-read
       (testing "the current reader decodes blobs written before the impl.nodes extraction"
         (doseq [[nm {:keys [bf elems root nodes]}] @golden]
           (testing nm
             (let [st (->GoldenStorage (atom nodes) bf)]
               (is (= elems (vec (set/restore root st)))
                   (str nm ": old on-disk bytes must still yield the right elements")))))))

     (deftest golden-blobs-are-byte-identical-on-rewrite
       (testing "re-encoding a decoded node reproduces the ORIGINAL bytes.

                 This is the half that catches a writer which reads old data fine
                 but emits a new shape — the failure that silently splits a
                 deployment as soon as one node upgrades."
         (doseq [[nm {:keys [bf nodes]}] @golden]
           (testing nm
             (doseq [[addr expected] nodes]
               (let [node (deser (unhex expected) (read-lookup bf))
                     got  (hex (ser node write-lookup))]
                 (is (= expected got)
                     (str nm "/" addr ": blob→node→blob must be byte-identical"))))))))

     (deftest golden-root-blob-still-reads
       (testing "the pss/set root blob — a pointer, whose shape is separate from the nodes'"
         (doseq [[nm {:keys [bf elems root-blob nodes]}] @golden]
           (testing nm
             (let [st (->GoldenStorage (atom nodes) bf)
                   lk (-> (merge fress/clojure-read-handlers
                                 (pss-fress/canonical-read-handlers
                                  {:default-bf bf
                                   :resolve-storage (constantly st)
                                   :resolve-cmp (constantly compare)
                                   :resolve-measure (constantly nil)
                                   :boundary-resolver bnd/boundary-from-descriptor}))
                          fress/associative-lookup)
                   s (deser (unhex root-blob) lk)]
               (is (instance? PersistentSortedSet s))
               (is (= elems (vec s)) (str nm ": root blob restores its elements")))))))

     (deftest golden-data-survives-mutation
       (testing "restore from old bytes, mutate, re-store with the CURRENT writer, read back"
         (doseq [[nm {:keys [bf elems root nodes]}] @golden]
           (testing nm
             (let [st (->GoldenStorage (atom nodes) bf)
                   s  (set/restore root st)
                   sentinel (if (string? (first elems)) "zzz-sentinel" 999999)
                   s2 (set/conj s sentinel compare)
                   a2 (set/store s2 st)]
               (is (= (conj elems sentinel) (vec (set/restore a2 st)))
                   (str nm ": old store + new writer round-trips")))))))))
